// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net_API.Datos;

#nullable disable

namespace Net_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Net_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Encanto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inquilinos")
                        .HasColumnType("int");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detalle = "Detalle de la Villa...",
                            Encanto = "",
                            FechaActualizacion = new DateTime(2023, 2, 14, 18, 49, 27, 675, DateTimeKind.Local).AddTicks(8846),
                            FechaCreacion = new DateTime(2023, 2, 14, 18, 49, 27, 675, DateTimeKind.Local).AddTicks(8815),
                            ImagenUrl = "",
                            Inquilinos = 5,
                            MetrosCuadrados = 50,
                            Nombre = "Villa Real",
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Detalle = "Detalle de la Villa...",
                            Encanto = "",
                            FechaActualizacion = new DateTime(2023, 2, 14, 18, 49, 27, 675, DateTimeKind.Local).AddTicks(8851),
                            FechaCreacion = new DateTime(2023, 2, 14, 18, 49, 27, 675, DateTimeKind.Local).AddTicks(8849),
                            ImagenUrl = "",
                            Inquilinos = 4,
                            MetrosCuadrados = 80,
                            Nombre = "Premium Vistas Piscina",
                            Tarifa = 400.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
